name: openid_client
description: Library for working with OpenID Connect and implementing clients.
version: 0.2.5
author: Rik Bellens <rik.bellens@appsup.be>
homepage: https://github.com/appsup-dart/openid_client

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  jose:
    git:
      url: git://github.com/renedecandido/jose.git
  http: ^0.12.2
  logging: ^0.11.4
  args: ^1.6.0

dev_dependencies:
  test: ^1.15.7
  angular: ^6.0.1
  build_runner: ^1.10.13
  build_web_compilers: ^2.11.0

executables:
  openid_client: openid_client